apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  metadata:
  - name: url
    value: https://dapr-bet-account.documents.azure.com:443/
  - name: masterKey
    value: 1x9emROeHUwc1fLoRMqZ77C3vQbvApj4isPuAWKSUOrIWkz3vRqZ7M1DrVSbDzj3iGC99P4e6WtfZVbKcET5KQ==
  - name: database
    value: bets
  - name: collection
    value: default