apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: signalr-output-binding
spec:
  type: bindings.azure.signalr
  metadata:
  - name: connectionString
    secretKeyRef:
      name: signalrConnectionString
  - name: hub
    value: daprbet
auth:
    secretStore: azurekeyvault