apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: punters-statestore
spec:
  type: state.azure.cosmosdb
  metadata:
  - name: url
    secretKeyRef:
      name: cosmosDbUrl
  - name: masterKey
    secretKeyRef:
      name: cosmosDbMasterKey
  - name: database
    value: punters
  - name: collection
    value: default
auth:
    secretStore: azurekeyvault