apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
  namespace: default
spec:
  type: secretstores.azure.keyvault
  metadata:
  - name: vaultName
    value: dapr-bet-kv
  - name: spnClientId
    value: c8467be6-4b68-4ccd-8a08-74382c0d2019