apiVersion: v1
kind: Service
metadata:
  name: races-service
  labels:
    app: races-service
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 8005
      protocol: TCP
      name: http
  selector:
    app: races
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: races
  labels:
    app: races
spec:
  replicas: 1
  selector:
    matchLabels:
      app: races
  template:
    metadata:
      labels:
        app: races
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "races"
        dapr.io/app-port: "8005"
        dapr.io/log-level: "debug"
        dapr.io/profiling: "true"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: races
          image: <IMAGE_NAME>
          ports:
            - containerPort: 8005
          imagePullPolicy: Always
          env:
            - name: COSMOS_DB_KEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-secrets
                  key: cosmos-db-master-key
            - name: COSMOS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: cosmos-secrets
                  key: cosmos-db-url
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
