apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-results
spec:
  secretTargetRef:
  - parameter: connection
    name: cosmos-db-secret
    key: sbConnectionString
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: results-scaler
  labels:
    app: results
    deploymentName: results
spec:
  scaleTargetRef:
    deploymentName: results
  pollingInterval: 5 # seconds
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: azure-servicebus
    metadata:
      topicName: results
      subscriptionName: results
      queueLength: "1"
    authenticationRef:
      name: trigger-auth-service-bus-results
