apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dapr-bet.kainiindustries.net
      secretName: tls-secret
  rules:
    - host: dapr-bet.kainiindustries.net
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: nginx-ingress-dapr
              port:
                number: 80

