apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding
  namespace: dapr-bet.bet
spec:
  type: bindings.azure.cosmosdb
  metadata:
  - name: url
    value: https://dapr-bet-account.documents.azure.com:443/
  - name: masterKey
    value: 1x9emROeHUwc1fLoRMqZ77C3vQbvApj4isPuAWKSUOrIWkz3vRqZ7M1DrVSbDzj3iGC99P4e6WtfZVbKcET5KQ==
  - name: database
    value: punters
  - name: collection
    value: default
  - name: partitionKey
    value: email