apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    value: Endpoint=sb://dapr-bet-sbus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=1AYvCFwXh35N/NX1C2Im27+ssHCpGMK6kLFlQHECI1s= # Required.
  - name: timeoutInSec
    value: 60 # Optional. Default: "60".
  - name: disableEntityManagement
    value: false # Optional. Default: false. When set to true, topics and subscriptions do not get created automatically.
#  - name: maxDeliveryCount
#    value: <REPLACE-WITH-MAX-DELIVERY-COUNT> # Optional.
#  - name: lockDurationInSec
#    value: <REPLACE-WITH-LOCK-DURATION-IN-SEC> # Optional.
#  - name: defaultMessageTimeToLiveInSec
#    value: <REPLACE-WITH-MESSAGE-TIME-TO-LIVE-IN-SEC> # Optional.
#  - name: autoDeleteOnIdleInSec
#    value: <REPLACE-WITH-AUTO-DELETE-ON-IDLE-IN-SEC> # Optional.
